name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*'  # This triggers the workflow on version tags, e.g., v1.0, v2.0.1

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify your Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine  # Install packages needed for building and uploading

    - name: Build the package
      run: python -m build  # Creates source and wheel distributions in the dist/ folder

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}  # Uses PyPI username from GitHub Secrets
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}  # Uses PyPI password from GitHub Secrets
      run: python -m twine upload dist/*
